/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carro;

import java.util.ArrayList;

/**
 *
 * @author USUARIO
 */
public class Visual extends javax.swing.JFrame {

    consecionario conse;

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlconsecionario = new javax.swing.JPanel();
        jlblnombre = new javax.swing.JLabel();
        jlblcodigo = new javax.swing.JLabel();
        jtxtnombre = new javax.swing.JTextField();
        jtxtcodigo = new javax.swing.JTextField();
        jbtnagregarconsecionario = new javax.swing.JButton();
        jlblnombreconsecionario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnagragarnuevo = new javax.swing.JButton();
        jlblnombrecarro = new javax.swing.JLabel();
        jlblcodigocarro = new javax.swing.JLabel();
        jlblcolorcarro = new javax.swing.JLabel();
        jlblmodelo = new javax.swing.JLabel();
        jlblcilindraje = new javax.swing.JLabel();
        jtxtnombrecarro = new javax.swing.JTextField();
        jtxtcodigocarro = new javax.swing.JTextField();
        jtxtcolorcarro = new javax.swing.JTextField();
        jtxtmodelo = new javax.swing.JTextField();
        jtxtcilindraje = new javax.swing.JTextField();
        jlblprecio = new javax.swing.JLabel();
        jtxtprecio = new javax.swing.JTextField();
        jlblcodigoconsecionario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtacarros = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlconsecionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblnombre.setText("nombre consecionario");

        jlblcodigo.setText("codigo consecionario");

        jtxtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreActionPerformed(evt);
            }
        });

        jbtnagregarconsecionario.setText("agregar");
        jbtnagregarconsecionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnagregarconsecionarioActionPerformed(evt);
            }
        });

        jlblnombreconsecionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnagragarnuevo.setText("nuevo");
        jbtnagragarnuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnagragarnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnagragarnuevoActionPerformed(evt);
            }
        });

        jlblnombrecarro.setText("nombre");

        jlblcodigocarro.setText("codigo");

        jlblcolorcarro.setText("color");

        jlblmodelo.setText("modelo");

        jlblcilindraje.setText("cilindraje");

        jtxtnombrecarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtnombrecarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombrecarroActionPerformed(evt);
            }
        });

        jtxtcodigocarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtcolorcarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtmodelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmodeloActionPerformed(evt);
            }
        });

        jtxtcilindraje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblprecio.setText("precio");

        jtxtprecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jbtnagragarnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblcodigocarro)
                            .addComponent(jlblnombrecarro))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigocarro)
                            .addComponent(jtxtnombrecarro)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblcolorcarro)
                            .addComponent(jlblmodelo)
                            .addComponent(jlblcilindraje)
                            .addComponent(jlblprecio))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtprecio)
                            .addComponent(jtxtcilindraje, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtmodelo)
                            .addComponent(jtxtcolorcarro))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblnombrecarro)
                    .addComponent(jtxtnombrecarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblcodigocarro)
                    .addComponent(jtxtcodigocarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblcolorcarro)
                    .addComponent(jtxtcolorcarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblmodelo)
                    .addComponent(jtxtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblcilindraje)
                    .addComponent(jtxtcilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblprecio)
                    .addComponent(jtxtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnagragarnuevo)
                .addGap(19, 19, 19))
        );

        jlblcodigoconsecionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtacarros.setColumns(20);
        jtxtacarros.setRows(5);
        jScrollPane2.setViewportView(jtxtacarros);

        javax.swing.GroupLayout jpnlconsecionarioLayout = new javax.swing.GroupLayout(jpnlconsecionario);
        jpnlconsecionario.setLayout(jpnlconsecionarioLayout);
        jpnlconsecionarioLayout.setHorizontalGroup(
            jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                        .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                                .addComponent(jlblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                                .addComponent(jlblcodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblcodigoconsecionario, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jlblnombreconsecionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83))
                    .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                        .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jbtnagregarconsecionario))
                            .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jpnlconsecionarioLayout.setVerticalGroup(
            jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblnombre)
                        .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblcodigoconsecionario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblcodigo)
                            .addComponent(jtxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jlblnombreconsecionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlconsecionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnlconsecionarioLayout.createSequentialGroup()
                        .addComponent(jbtnagregarconsecionario)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jpnlconsecionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jpnlconsecionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreActionPerformed

    private void jbtnagregarconsecionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnagregarconsecionarioActionPerformed


        //  jtxtcodigo.setText("hola ");//

        int id = Integer.parseInt(jtxtcodigo.getText());
        String nombre = jtxtnombre.getText();

        conse = new consecionario(nombre, id);
        jbtnagregarconsecionario.setEnabled(false);// se pone setenable false para que solo se de click una vez y ya no pueda crear mas
        jlblcodigoconsecionario.setText(String.valueOf(conse.Getid()));
        jlblnombreconsecionario.setText(conse.Getnombre());

    }//GEN-LAST:event_jbtnagregarconsecionarioActionPerformed

    private void jtxtnombrecarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombrecarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombrecarroActionPerformed

    private void jtxtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmodeloActionPerformed

    private void jbtnagragarnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnagragarnuevoActionPerformed
        String nombre = jtxtnombrecarro.getText();
        int codigo = Integer.parseInt(jtxtcodigo.getText());
        String color = jtxtcolorcarro.getText();
        int modelo = Integer.parseInt(jtxtmodelo.getText());
        int cilindraje = Integer.parseInt(jtxtcilindraje.getText());
        int precio = Integer.parseInt(jtxtprecio.getText());
        carro car = new carro(codigo, nombre, color, cilindraje, modelo, modelo);
        conse.Agregarcarro(car);
        jbtnagragarnuevo.setEnabled(false);
        obtenerlista();
    }//GEN-LAST:event_jbtnagragarnuevoActionPerformed

    public void obtenerlista() {
        ArrayList<carro> carros = conse.obtenerlista();
        String mensaje = "";
        for (carro carro : carros) {
            mensaje += carro.Getnombre() + " " + carro.Getmodelo() + "\n";

        }
        jtxtacarros.setText(mensaje);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnagragarnuevo;
    private javax.swing.JButton jbtnagregarconsecionario;
    private javax.swing.JLabel jlblcilindraje;
    private javax.swing.JLabel jlblcodigo;
    private javax.swing.JLabel jlblcodigocarro;
    private javax.swing.JLabel jlblcodigoconsecionario;
    private javax.swing.JLabel jlblcolorcarro;
    private javax.swing.JLabel jlblmodelo;
    private javax.swing.JLabel jlblnombre;
    private javax.swing.JLabel jlblnombrecarro;
    private javax.swing.JLabel jlblnombreconsecionario;
    private javax.swing.JLabel jlblprecio;
    private javax.swing.JPanel jpnlconsecionario;
    private javax.swing.JTextArea jtxtacarros;
    private javax.swing.JTextField jtxtcilindraje;
    private javax.swing.JTextField jtxtcodigo;
    private javax.swing.JTextField jtxtcodigocarro;
    private javax.swing.JTextField jtxtcolorcarro;
    private javax.swing.JTextField jtxtmodelo;
    private javax.swing.JTextField jtxtnombre;
    private javax.swing.JTextField jtxtnombrecarro;
    private javax.swing.JTextField jtxtprecio;
    // End of variables declaration//GEN-END:variables
}
